cws_quill_js:
    enabled: true
    config_name: default
    theme: ~
    js_source: ~
    css_source: ~
    edit_html: true
    toolbar:
        default:
            - [ 'bold', 'italic', 'underline', 'strike' ]
            - [ 'blockquote', 'code-block' ]
            - [ 'link', 'video', 'formula' ]
            - [ { 'header': 1 }, { 'header': 2 } ]
            - [ { 'list': 'ordered' }, { 'list': 'bullet' }, { 'list': 'check' } ]
            - [ { 'script': 'sub' }, { 'script': 'super' } ]
            - [ { 'indent': '-1' }, { 'indent': '+1' } ]
            - [ { 'direction': 'rtl' } ]
            - [ { 'size': [ 'small', false, 'large', 'huge' ] } ]
            - [ { 'header': [ 1, 2, 3, 4, 5, 6, false ] } ]
            - [ { 'color': [ ] }, { 'background': [ ] } ]
            - [ { 'font': [ ] } ]
            - [ { 'align': [ ] } ]
            - [ 'clean' ]
